"""empty message

Revision ID: 69379e119b2f
Revises: 7404a3ab8263
Create Date: 2022-08-12 16:47:30.096085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69379e119b2f'
down_revision = '7404a3ab8263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('artist_website_link_key', 'artist', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('artist_website_link_key', 'artist', ['website_link'])
    # ### end Alembic commands ###
