"""empty message

Revision ID: 7404a3ab8263
Revises: 490aa6d622ad
Create Date: 2022-08-12 04:13:25.304448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7404a3ab8263'
down_revision = '490aa6d622ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'artist_image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('artist_image_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
